#!/usr/bin/env sh

_jumpAndRunCommands() {
  case "$1" in
    "wxapp")
      cd ~/Workspace/mt/youxuan/mall-wxapp
    ;;
    "github")
      cd ~/Workspace/github
    ;;
    "clones")
      cd ~/Workspace/clones
    ;;
    *)
      cd "$1"
    ;;
  esac
}
_goCompletion() {
  # https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2
  local cur prev opts
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="wxapp github clones"

  # https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html
  COMPREPLY=( $(compgen -o "dirnames" -W "${opts}" -- ${cur}) )
}
alias go=_jumpAndRunCommands
complete -F _goCompletion go
