#!/usr/bin/env sh

_jumpAndRunCommands() {
  case "$1" in
    "web")
      cd ~/usr/src/mt/dx-web
      nvm use 5
    ;;
    "pc")
      cd ~/usr/src/mt/dx-pc/pc-elephant-electron
      nvm use 6
      npm run platform
    ;;
    "self")
      cd ~/usr/src/self
    ;;
    "clones")
      cd ~/usr/src/clones
    ;;
    "weekly")
      cd ~/usr/src/mt/weekly/source/_posts
    ;;
    "etc")
      cd ~/etc
    ;;
    "vim")
      cd ~/.vim/bundle
    ;;
    "downloads")
      cd ~/Downloads
    ;;
    "documents")
      cd ~/Documents
    ;;
    "playground")
      cd ~/usr/src/playground
    ;;
    *)
      cd "$1"
    ;;
  esac
}
_goCompletion() {
  # https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2
  local cur prev opts
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="web pc self clones weekly playground etc vim downloads documents"

  # https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html
  COMPREPLY=( $(compgen -o "dirnames" -W "${opts}" -- ${cur}) )
}
alias go=_jumpAndRunCommands
complete -F _goCompletion go
