#!/bin/sh
# 管理已有的bundle
manage_bundles() {
    local SRC_VUNDLE_DIR=$USR_ETC_DIR/vim/bundle
    local TARGET_VUNDLE_DIR=$HOME/.vim/bundle
    echo "src: $SRC_VUNDLE_DIR"
    echo "target: $TARGET_VUNDLE_DIR"
    if [[ !(-d "$TARGET_VUNDLE_DIR") ]]; then
        echo "executing: mkdir -p $TARGET_VUNDLE_DIR ... "
        mkdir -p "$TARGET_VUNDLE_DIR"
        echo "...done."
    fi
    if [[ !(-d "$SRC_VUNDLE_DIR") ]]; then
        echo "executing: mkdir -p $SRC_VUNDLE_DIR ... "
        mkdir -p "$SRC_VUNDLE_DIR"
        echo "...done."
    fi
    local option="add"
    while [[ $# -gt 0 ]]; do
        case $1 in
            -a)
                option="add"
                ;;
            -d)
                option="remove"
                ;;
            *)
                if [[ $option == "add" ]]; then
                    if [[ -d "$SRC_VUNDLE_DIR/$1" ]]; then
                        if [[ -d "$TARGET_VUNDLE_DIR/$1" ]]; then
                            echo "$TARGET_VUNDLE_DIR/$1 already exists."
                        else
                            echo "executing: mv $SRC_VUNDLE_DIR/$1 $TARGET_VUNDLE_DIR/$1 ... "
                            mv "$SRC_VUNDLE_DIR/$1" "$TARGET_VUNDLE_DIR/$1"
                            echo "...done."
                        fi
                    else
                        echo "$SRC_VUNDLE_DIR/$1 does not exist."
                    fi
                else
                    if [[ -d "$TARGET_VUNDLE_DIR/$1" ]]; then
                        echo "executing: mv $TARGET_VUNDLE_DIR/$1 $SRC_VUNDLE_DIR/$1 ... "
                        mv "$TARGET_VUNDLE_DIR/$1" "$SRC_VUNDLE_DIR/$1"
                        echo "...done."
                    else
                        echo "$TARGET_VUNDLE_DIR/$1 does not exist."
                    fi
                fi
                ;;
        esac
        shift
    done
}

manage_bundles \
    Vundle.vim \
    nerdtree \
    vim-autoclose \
    vim-markdown \
    vim-stylus \
    vim-javascript \
    html5.vim \
    scss-syntax.vim \
    vim-surround \
    vim-snippets

manage_bundles -d \
    ultisnips \
    emmet-vim

add_color() {
    local SRC_COLORS_DIR=$USR_ETC_DIR/vim/colors
    local TARGET_COLORS_DIR=$HOME/.vim/colors
    if [[ !(-d "$TARGET_COLORS_DIR") ]]; then
        echo "executing: mkdir -p $TARGET_COLORS_DIR ... "
        mkdir -p "$TARGET_COLORS_DIR"
        echo "...done."
    fi
    if [[ -f "$SRC_COLORS_DIR/$1" ]]; then
        if [[ -f "$TARGET_COLORS_DIR/$1" ]]; then
            echo "$TARGET_COLORS_DIR/$1 already exists."
        else
            echo "executing: ln -s $SRC_COLORS_DIR/$1 $TARGET_COLORS_DIR/$1 ... "
            ln -s "$SRC_COLORS_DIR/$1" "$TARGET_COLORS_DIR/$1"
            echo "...done."
        fi
    else
        echo "$SRC_COLORS_DIR/$1 does not exist."
    fi
}
add_color solarized.vim
