# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# 设置后，可以保证vim退出时不遗留内容
export TERM=xterm-256color
export PATH="/opt/homebrew/bin:$PATH"

# [ -f `brew --prefix`/etc/bash_completion ] && . `brew --prefix`/etc/bash_completion
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

unset file
